### ISSUE TITLE
Issue defining pin and wire instance

### ISSUE THREAD

**Issue by etded** [stm32duino/ST25DV#17]
I have a question about the pin assignment in the ST25DV_HelloWorld.ino program.

I am using the ST25DV 8-pins package and according to the datasheet there is no LPD pin so I do not understand what pin to assign to the variable LPD_PIN in the program. I tried using the V_EH pin and assigning to LPD_PIN the corresponding pin of the microcontroller but this results in "System Init failed!" in the serial monitor.

I have searched in the stm32duino/ST25DV documentation but have not found anything relevant to this topic.

Can somebody help me with this issue?

**Comment by fpistm** [comment]
Answered here: https://www.stm32duino.com/viewtopic.php?f=7&t=1640
