### ISSUE TITLE
use with adafruit trinkey RP2040 QT usb

### ISSUE THREAD

**Issue by BilalChouaibi** [stm32duino/ST25DV#23]
Does it work with this board https://learn.adafruit.com/adafruit-trinkey-qt2040/pinouts
and st25dv16 https://learn.adafruit.com/adafruit-st25dv16k-i2c-rfic-eeprom-breakout
????

**Comment by cparata** [comment]
Hello @BilalChouaibi ,
I think that the Adafruit st25dv16 board should be compatible with this library as it is written in the link that you have shared. I don't know the Adafruit Trinkey QT2040 board but if this platform is supported in the Arduino IDE, you could use it as well without any issue.
Best Regards,
Carlo
