### ISSUE TITLE
re: adafruit qt2040 qt

### ISSUE THREAD

**Issue by BilalChouaibi** [stm32duino/ST25DV#24]
how can i define sda and scl pin of this product? https://learn.adafruit.com/adafruit-trinkey-qt2040/pinouts
I test it last week but it didn't work with this card and this module https://learn.adafruit.com/adafruit-st25dv16k-i2c-rfic-eeprom-breakout
😭😭😭😭😭😭

**Comment by cparata** [comment]
Hello @BilalChouaibi ,
how did you connect the 2 boards? You must connect also the GPO pin, not only the SDA and SCL pins to get the tag working.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Closed as long time without answer from OP except a thumb up.
