### ISSUE TITLE
Non ardunio library.

### ISSUE THREAD

**Issue by jkbbwr** [stm32duino/ST25DV#27]
Im working against RP2040 Pico W and using the pure C/C++ SDK. 
I was wondeirng if there is going to be a pure C i2c implementation without relying on the arduino bootloader?

I need to be able to read RFID tags.

**Comment by cparata** [comment]
Hello @jkbbwr ,
unfortunately, this library is done for the Arduino framework. You can ask support on [ST Community](https://community.st.com/s/) about pure C implementation.
Best Regards,
Carlo
