### ISSUE TITLE
VCard `END` define conflicts with dsu.h

### ISSUE THREAD

**Issue by maihde** [stm32duino/ST25DV#28]
I recently upgraded to library version 2.0.2 (from 1.0.1).  With Ardunio version 2.11 and a MKR1000 board, I get these compilation errors.

```
lib_NDEF_Vcard.h:63:39: error: expected unqualified-id before string constant
 #define END                           "END:"
 ```

```
MSIS-Atmel\1.2.0/CMSIS/Device/ATMEL/samd21/include/component/dsu.h:293:14: note: in expansion of macro 'END'
     uint32_t END:32;           /*!< bit:  0..31  End Marker                         */
```

I fixed it by changing `lib_NDEF_Vcard.h` to use `#define VCARD_END` to avoid conflicts.

**Comment by cparata** [comment]
Hello @maihde ,
thanks for submitting the issue. I solved it in the main branch and released a new version of the library with the fix (v2.0.3).
Best Regards,
Carlo
