### ISSUE TITLE
Missing "NDEF::" in NDEF_WriteRecord method definition

### ISSUE THREAD

**Issue by MOUMOUDOU** [stm32duino/ST25DV#33]
Hi, I noticed an error in the lib_NDEF.cpp file on line 613, the class name :

> "NDEF::"

Is missing before the method :

> "NDEF_WriteRecord"

https://github.com/stm32duino/ST25DV/blob/26f27d55ef5412872f73b3aac1dd50587d1471b9/src/libNDEF/lib_NDEF.cpp#L613

Error message at compilation:
`libraries\STM32duino_ST25DV\src\libNDEF/lib_NDEF.cpp:528: undefined reference to NDEF::NDEF_WriteRecord(sRecordInfo*, unsigned char*)
collect2.exe: error: ld returned 1 exit status`

**Comment by cparata** [comment]
Hi @MOUMOUDOU ,
thanks a lot to have submitted this issue. I fixed it in the new release v2.1.1.
Best Regards,
Carlo
