### ISSUE TITLE
Examples folder not present in 1.0.1 release

### ISSUE THREAD

**Issue by jdimpson** [stm32duino/ST25DV#7]
Is there any chance that in future releases, the examples/ folder can be included? According to my understanding of [https://arduino.github.io/arduino-cli/latest/library-specification/](https://arduino.github.io/arduino-cli/latest/library-specification/) it looks like you can just include the examples/ folder at the same level as the src/ folder, and the Arduino IDE will make them available under File->Examples->STM32duino ST25DV->

**Comment by fpistm** [comment]
Hi @jdimpson 
yes there is chance to have example.
They were already available in the master. I've made a new release 1.0.2 which includes them.
