### ISSUE TITLE
Any chance we can get some code for raspberry pi use?

### ISSUE THREAD

**Issue by snarflakes** [stm32duino/ST25DV#9]
Great device! I'm interested in tinkering with this on my raspberry pi. Would a pi conversion be difficult? Is it on a to-do list? I presume the driver code would need to be converted to python? How hard would it be to interface with the device via an arduino virtual environment?
 
thanks!

**Comment by fpistm** [comment]
Hi @snarflakes 

There is no plan for this. This is an Arduino library. You can try to made the porting but we could not provide any advice nor difficulty as we don't know Raspberry environment. 
You can try to open a topic on this subject on the forum hhtps://www.stm32duino.com maybe some users will have some inputs.

About using Arduino on raspberry Pi some user succeeds. I have in my to do list to support it but I currently have no time to work on this soon.

https://github.com/stm32duino/Arduino_Core_STM32/issues/708
